%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/girasole/liblinear/my_output.txt
%
% Auto-generated by MATLAB on 13-Jan-2021 00:25:00

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName2";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/Users/girasole/liblinear/my_output.txt", opts);

%% Convert to output type
freqs = tbl.VarName2;

%% Clear temporary variables
clear opts tbl


%%

n = 1000; 
B = 1/n*ones(n,1);
out = filter(B,1,freqs);
figure(1);clf;
plot(out);